// Package presenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package presenter

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StatusName.
const (
	Archive    StatusName = "archive"
	Done       StatusName = "done"
	InProgress StatusName = "inProgress"
	Pending    StatusName = "pending"
	Todo       StatusName = "todo"
)

// ApiVersion defines model for ApiVersion.
type ApiVersion = string

// CreateTaskRequestBody defines model for CreateTaskRequestBody.
type CreateTaskRequestBody struct {
	Kind   *string `json:"kind,omitempty"`
	Name   string  `json:"name"`
	Status Status  `json:"status"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// CsrfTokenResponse defines model for CsrfTokenResponse.
type CsrfTokenResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       CsrfToken  `json:"data"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// LoginRequestBody defines model for LoginRequestBody.
type LoginRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpRequestBody defines model for SignUpRequestBody.
type SignUpRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       User       `json:"data"`
}

// Status defines model for Status.
type Status struct {
	Id   *int       `json:"id,omitempty"`
	Name StatusName `json:"name"`
}

// StatusName defines model for Status.Name.
type StatusName string

// Task defines model for Task.
type Task struct {
	Id     int    `json:"id"`
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Status Status `json:"status"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       Task       `json:"data"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       []Task     `json:"data"`
}

// UpdateTaskRequestBody defines model for UpdateTaskRequestBody.
type UpdateTaskRequestBody struct {
	Kind   *string `json:"kind,omitempty"`
	Name   string  `json:"name"`
	Status Status  `json:"status"`
}

// User defines model for User.
type User struct {
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`
	Email     string              `json:"email"`
	Id        *int                `json:"id,omitempty"`
	Kind      string              `json:"kind"`
	Password  *string             `json:"password,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequestBody

// PostSignUpJSONRequestBody defines body for PostSignUp for application/json ContentType.
type PostSignUpJSONRequestBody = SignUpRequestBody

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequestBody

// UpdateTaskByIdJSONRequestBody defines body for UpdateTaskById for application/json ContentType.
type UpdateTaskByIdJSONRequestBody = UpdateTaskRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get CSRF token
	// (GET /csrf)
	GetCsrfToken(c *gin.Context)
	// Login
	// (POST /login)
	PostLogin(c *gin.Context)
	// Logout
	// (POST /logout)
	PostLogout(c *gin.Context)
	// Sign up
	// (POST /signup)
	PostSignUp(c *gin.Context)
	// Get all tasks
	// (GET /tasks)
	GetAllTasks(c *gin.Context)
	// Create a new task
	// (POST /tasks)
	CreateTask(c *gin.Context)
	// Delete task by ID
	// (DELETE /tasks/{id})
	DeleteTaskById(c *gin.Context, id int)
	// Get task by ID
	// (GET /tasks/{id})
	GetTaskById(c *gin.Context, id int)
	// Update task by ID
	// (PATCH /tasks/{id})
	UpdateTaskById(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCsrfToken operation middleware
func (siw *ServerInterfaceWrapper) GetCsrfToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCsrfToken(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogout(c)
}

// PostSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignUp(c)
}

// GetAllTasks operation middleware
func (siw *ServerInterfaceWrapper) GetAllTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTasks(c)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c)
}

// DeleteTaskById operation middleware
func (siw *ServerInterfaceWrapper) DeleteTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTaskById(c, id)
}

// GetTaskById operation middleware
func (siw *ServerInterfaceWrapper) GetTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTaskById(c, id)
}

// UpdateTaskById operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTaskById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/csrf", wrapper.GetCsrfToken)
	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.POST(options.BaseURL+"/logout", wrapper.PostLogout)
	router.POST(options.BaseURL+"/signup", wrapper.PostSignUp)
	router.GET(options.BaseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(options.BaseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(options.BaseURL+"/tasks/:id", wrapper.DeleteTaskById)
	router.GET(options.BaseURL+"/tasks/:id", wrapper.GetTaskById)
	router.PATCH(options.BaseURL+"/tasks/:id", wrapper.UpdateTaskById)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3W7jNhN9FYHfdylY9u4WXeguybaFgaII4qQ3C6PgSmObG4nkkiMvjEDvXgwp/0m0",
	"rS5iJy2C3NgROXPmzJkf+YllqtRKgkTL0idmswWU3H280uJPMFYoSd9ymPGqQJay5YjFDFcaWMosGiHn",
	"rI7ZjQGOcM/t4x18q8DitcpXdFEbpcGgAGf0Uch83xxy+xgyKHkJdLLzwCLHyhn7v4EZS9n/km0MSRNA",
	"MvGn6jpmBr5VwkDO0s/e6sbGdONXffkKGbpArJndq0eQQeebp3dgtZIWuiHyPd6OYdxhuI5ZzpGfurEF",
	"1w5sx2tjKhTcL8Yo04WcqXyXayER5mDoQgnW8nkoES3/64OxN3bQ+WHeYI3tGAE+gLZzfzXk83c1F/If",
	"KrKyYEKKdP8/ge+BzrThuYshdBMxlw/61cN7CaUHkfYT+WTTIPbhijys8XWnAVmV5AVVrljMhLw1am7A",
	"WnKmJGmbm2whlvRJg8yJ+Gl8ojCc9RBM6pX9Qb5043T+Y4IX92iifg68hG4cqz+mG7pqz4daIJS2H/wN",
	"OG4MX/1gOA86/29M5IemsbVmlls48r840reZMiV9IjogBB5KLoog+v4Vd6jzam7td2Xy01OyqSIPphsr",
	"HRdyppwhgQU9u1e5iq5uxyxmy7X82GgwHAzJtdIguRYsZe8Hw8F7akwcF46gJLNmRh/m4Cgi8jgKJcc5",
	"S9lvgNtlgkB62bub74ZDvxVIBIle+7oQmbudfLW+Anxee28sm8JyUeZgMyM0+nAmVZaBtbOqiMz2WMxs",
	"VZbcrDzc6GZy92uEDWDkc0uMuiCndDgpaNY7oSgbiPhWWXTrAPM52amIZ4m0s2rU+9lHU0EdZvogGz6k",
	"OmYfnjEl+3tYIB3XPI8ahsj3T5f0PZYIRvIismCWYCLYLHxbMayzuNYA1aXdikBVeFIFdKZPLv5Q0U0T",
	"dweDtxECYcVcVvo4CL9cnUmL3cWylxhHzw6gV80TXVGl33Te0tik4SUsMhrT9lh/vyoKt9Kcs73v70x9",
	"W/sr5JoGDC+KCBvG1oz771Oa8sFS3v7ucaZSDv+wcuFy3tvnAwzT86jZyCK7SXmxeqvpls58OiMeSfge",
	"rTftltY21Z08ibz2Q6kAhK76Prn/E/vXq3Hutj/DS0DqEunnJ0b7kNsI129tqX+D21dOvENAew+upx1Z",
	"feiOSZd/D7Kb/1eXA8+aYz/6sorGn4L1fqitXpjt4cWK+N/Uqk/kTnPMFt3sbV+Jz5vA558C4Zf5/m8Y",
	"l5sClUP6NgWOStin87iK3Q1nwouzMgVL2QJRp0kyHLi/9OPw4zDhWiTLEavj1qFCZbxYKIvHj43e/eys",
	"jfaPTeu/AwAA///1SMS0HRoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
