// Package presenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package presenter

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StatusName.
const (
	Archive    StatusName = "archive"
	Done       StatusName = "done"
	InProgress StatusName = "inProgress"
	Pending    StatusName = "pending"
	Todo       StatusName = "todo"
)

// ApiVersion defines model for ApiVersion.
type ApiVersion = string

// CreateTaskRequestBody defines model for CreateTaskRequestBody.
type CreateTaskRequestBody struct {
	Deadline *Deadline `json:"deadline,omitempty"`
	Kind     *string   `json:"kind,omitempty"`
	Name     string    `json:"name"`
	Status   Status    `json:"status"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// CsrfTokenResponse defines model for CsrfTokenResponse.
type CsrfTokenResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       CsrfToken  `json:"data"`
}

// Deadline defines model for Deadline.
type Deadline = openapi_types.Date

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// LoginRequestBody defines model for LoginRequestBody.
type LoginRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpRequestBody defines model for SignUpRequestBody.
type SignUpRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       User       `json:"data"`
}

// Status defines model for Status.
type Status struct {
	Id   *int       `json:"id,omitempty"`
	Name StatusName `json:"name"`
}

// StatusName defines model for Status.Name.
type StatusName string

// Task defines model for Task.
type Task struct {
	Deadline *Deadline `json:"deadline,omitempty"`
	Id       int       `json:"id"`
	Kind     string    `json:"kind"`
	Name     string    `json:"name"`
	Status   Status    `json:"status"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       Task       `json:"data"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       []Task     `json:"data"`
}

// UpdateTaskRequestBody defines model for UpdateTaskRequestBody.
type UpdateTaskRequestBody struct {
	Deadline *Deadline `json:"deadline,omitempty"`
	Kind     *string   `json:"kind,omitempty"`
	Name     string    `json:"name"`
	Status   Status    `json:"status"`
}

// User defines model for User.
type User struct {
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`
	Email     string              `json:"email"`
	Id        *int                `json:"id,omitempty"`
	Kind      string              `json:"kind"`
	Password  *string             `json:"password,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequestBody

// PostSignUpJSONRequestBody defines body for PostSignUp for application/json ContentType.
type PostSignUpJSONRequestBody = SignUpRequestBody

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequestBody

// UpdateTaskByIdJSONRequestBody defines body for UpdateTaskById for application/json ContentType.
type UpdateTaskByIdJSONRequestBody = UpdateTaskRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get CSRF token
	// (GET /csrf)
	GetCsrfToken(c *gin.Context)
	// Login
	// (POST /login)
	PostLogin(c *gin.Context)
	// Logout
	// (POST /logout)
	PostLogout(c *gin.Context)
	// Sign up
	// (POST /signup)
	PostSignUp(c *gin.Context)
	// Get all tasks
	// (GET /tasks)
	GetAllTasks(c *gin.Context)
	// Create a new task
	// (POST /tasks)
	CreateTask(c *gin.Context)
	// Delete task by ID
	// (DELETE /tasks/{id})
	DeleteTaskById(c *gin.Context, id int)
	// Get task by ID
	// (GET /tasks/{id})
	GetTaskById(c *gin.Context, id int)
	// Update task by ID
	// (PATCH /tasks/{id})
	UpdateTaskById(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCsrfToken operation middleware
func (siw *ServerInterfaceWrapper) GetCsrfToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCsrfToken(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogout(c)
}

// PostSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignUp(c)
}

// GetAllTasks operation middleware
func (siw *ServerInterfaceWrapper) GetAllTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTasks(c)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c)
}

// DeleteTaskById operation middleware
func (siw *ServerInterfaceWrapper) DeleteTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTaskById(c, id)
}

// GetTaskById operation middleware
func (siw *ServerInterfaceWrapper) GetTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTaskById(c, id)
}

// UpdateTaskById operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTaskById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/csrf", wrapper.GetCsrfToken)
	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.POST(options.BaseURL+"/logout", wrapper.PostLogout)
	router.POST(options.BaseURL+"/signup", wrapper.PostSignUp)
	router.GET(options.BaseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(options.BaseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(options.BaseURL+"/tasks/:id", wrapper.DeleteTaskById)
	router.GET(options.BaseURL+"/tasks/:id", wrapper.GetTaskById)
	router.PATCH(options.BaseURL+"/tasks/:id", wrapper.UpdateTaskById)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/jNhD9KwLboxA53e1Ft3y0hYGiCOKkl4VRcMWxwo1EcjmUF0ag/16QlGRbom0h",
	"sJ0UzU22SM6bN28+qBeSyVJJAcIgSV8IZk9QUvd4pfjfoJFLYX8xWNCqMCQly0sSE7NSQFKCRnORkzom",
	"NxqogQeKz/fwvQI015Kt7EalpQJtOKA/hrKCC7DPP2tYkJT8lKwhJI395LZdV8fkmQu2DcFQfA6BELR0",
	"Jw9eoKGmwkNGZ35VXcdEw/eKa2Ak/eJP7c6Yd3bl12+QGec86sWDfAYRNN69vQdUUiAMaaFbXO/DuBGV",
	"OiaMGnpoxxpc37ENq81RIeduN0K2kLqkNgKMGghF4DetpR76l0m2GRguDOSg7YYSEGkeiloPbLsw9oeF",
	"kDrju0mGFts+trwDfeN+a8jmnzLnYq/kh/KtEHSIPPf/AXyPdk0fntsYQjfjuXhU7x7eW6RFEOm4jJh1",
	"1WQbLmdhjbdlCURVWitGMkliwsWdlrkGRGtMCqttqrMnvrRPCgSzxM/jA4nhTg/BtMX4OBV4l2NvXZmd",
	"fQcvHlGlfXN6C625SLxOa3Yrng41N1DiOPgdOKo1Xb3SnUfF/r9jwmNTQHu90U1O7B/bV0d0WCgpL4Lo",
	"x2fprgqvKOIPqdnhbtxkngcz9NUu52Ih3UHcFPbdg2QyurqbkpgsW8mSy4vJxcSalgoEVZyk5NPF5OKT",
	"LYDUPDmCkgz1wj7k4Ciy5FHDpZgykpI/wKwnHAvSp4rb+ctk4qcPYUAYny+q4JnbnXxDnzU+rqPHqC4Z",
	"nZcMMNNcGe/OrMoyQFxURaTXy2KCVVlSvfJwo5vZ/e+RaQAbmqNl1Dk5t4uTws4UTigSAx7fSTRu7CA+",
	"JhtZdBRPByNNvR19oyuow0zvZMO7VMfk8xFDsj3vBcJxTVnUMGRt/3pO21NhQAtaRAh6CTqCbrBci6GN",
	"YqsBm5e4FoGszEEV2DVjYvGXjG4avwcY/BkhEMhzUan9IPwQdyItDgfYUWK8PDqAUTlv6Yoq9aHznsZm",
	"DS9hkdk2jfvq+1VRuDHolOV9e84aW9rfIde2wdCiiEzDWMu4/z23XT6YyusPOCdK5fAXojOn89YdIMCw",
	"fR81E1mEXciL1UdO93TmwxnRSMCPqJ20e1rrsjt54az2TakAA0P13br/LfvXqylz05+mJRhbJdIvL8TO",
	"Q24ibG96qb/1bSsn3iCgPwfX84GsPg/bpIu/BzmM/7uLgWfNsR99XUXT22C+7yqrZ2Z7crYk/i+V6gOx",
	"U9RkT8Pora/Rpw3g8btA+APA+BvG+bpA5ZB+dIG9Evbh3K9it8Md4cVZ6YKkJKGKJ8tLUs/rfwMAAP//",
	"4y/EjoUaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
