// Package presenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package presenter

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StatusName.
const (
	Archive    StatusName = "archive"
	Done       StatusName = "done"
	InProgress StatusName = "inProgress"
	Pending    StatusName = "pending"
	Todo       StatusName = "todo"
)

// ApiVersion defines model for ApiVersion.
type ApiVersion = string

// CreateTaskRequestBody defines model for CreateTaskRequestBody.
type CreateTaskRequestBody struct {
	Kind   *string `json:"kind,omitempty"`
	Name   string  `json:"name"`
	Status Status  `json:"status"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// CsrfTokenResponse defines model for CsrfTokenResponse.
type CsrfTokenResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       CsrfToken  `json:"data"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// LoginRequestBody defines model for LoginRequestBody.
type LoginRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpRequestBody defines model for SignUpRequestBody.
type SignUpRequestBody struct {
	Kind *string `json:"kind,omitempty"`
	User User    `json:"user"`
}

// SignUpResponse defines model for SignUpResponse.
type SignUpResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       User       `json:"data"`
}

// Status defines model for Status.
type Status struct {
	Id   *int       `json:"id,omitempty"`
	Name StatusName `json:"name"`
}

// StatusName defines model for Status.Name.
type StatusName string

// Task defines model for Task.
type Task struct {
	Id     int    `json:"id"`
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Status Status `json:"status"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       Task       `json:"data"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	ApiVersion ApiVersion `json:"apiVersion"`
	Data       []Task     `json:"data"`
}

// UpdateTaskRequestBody defines model for UpdateTaskRequestBody.
type UpdateTaskRequestBody struct {
	Kind   *string `json:"kind,omitempty"`
	Name   string  `json:"name"`
	Status Status  `json:"status"`
}

// User defines model for User.
type User struct {
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`
	Email     string              `json:"email"`
	Id        *int                `json:"id,omitempty"`
	Kind      string              `json:"kind"`
	Password  *string             `json:"password,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequestBody

// PostSignUpJSONRequestBody defines body for PostSignUp for application/json ContentType.
type PostSignUpJSONRequestBody = SignUpRequestBody

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequestBody

// UpdateTaskByIdJSONRequestBody defines body for UpdateTaskById for application/json ContentType.
type UpdateTaskByIdJSONRequestBody = UpdateTaskRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get CSRF token
	// (GET /csrf)
	GetCsrfToken(c *gin.Context)
	// Login
	// (POST /login)
	PostLogin(c *gin.Context)
	// Logout
	// (POST /logout)
	PostLogout(c *gin.Context)
	// Sign up
	// (POST /signup)
	PostSignUp(c *gin.Context)
	// Get all tasks
	// (GET /tasks)
	GetAllTasks(c *gin.Context)
	// Create a new task
	// (POST /tasks)
	CreateTask(c *gin.Context)
	// Delete task by ID
	// (DELETE /tasks/{id})
	DeleteTaskById(c *gin.Context, id int)
	// Get task by ID
	// (GET /tasks/{id})
	GetTaskById(c *gin.Context, id int)
	// Update task by ID
	// (PATCH /tasks/{id})
	UpdateTaskById(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCsrfToken operation middleware
func (siw *ServerInterfaceWrapper) GetCsrfToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCsrfToken(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogout(c)
}

// PostSignUp operation middleware
func (siw *ServerInterfaceWrapper) PostSignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignUp(c)
}

// GetAllTasks operation middleware
func (siw *ServerInterfaceWrapper) GetAllTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTasks(c)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c)
}

// DeleteTaskById operation middleware
func (siw *ServerInterfaceWrapper) DeleteTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTaskById(c, id)
}

// GetTaskById operation middleware
func (siw *ServerInterfaceWrapper) GetTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTaskById(c, id)
}

// UpdateTaskById operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskById(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTaskById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/csrf", wrapper.GetCsrfToken)
	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.POST(options.BaseURL+"/logout", wrapper.PostLogout)
	router.POST(options.BaseURL+"/signup", wrapper.PostSignUp)
	router.GET(options.BaseURL+"/tasks", wrapper.GetAllTasks)
	router.POST(options.BaseURL+"/tasks", wrapper.CreateTask)
	router.DELETE(options.BaseURL+"/tasks/:id", wrapper.DeleteTaskById)
	router.GET(options.BaseURL+"/tasks/:id", wrapper.GetTaskById)
	router.PATCH(options.BaseURL+"/tasks/:id", wrapper.UpdateTaskById)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/jNhD9KwLboxA53e1FtyTbFgaKIoiTXhZGwRXHCjcSySUpL4xA/70YUpJtibbV",
	"wHbSRW5yRM68efPmQ3kmmSyVFCCsIekzMdkjlNQ9Xin+N2jDpcBfDBa0KixJyfKSxMSuFJCUGKu5yEkd",
	"kxsN1MI9NU938K0CY68lW+FFpaUCbTk4o09csG1zlpqnkEFBS8CTgxfGUls5Yz9rWJCU/JSsY0iaAJKZ",
	"P1XXMdHwreIaGEk/e6udjXnnV375Cpl1gRi9uJdPIILOu7d3YJQUBoYh0i3e9mHcYLiOCaOWHrqxBtcP",
	"bMNrYyoU3G9aSz2EnEm2yTUXFnLQeKEEY2geSkTPf3sw9sZ2Ot/NG7TY9hHgA+g791dDPv+UORf/UZGV",
	"AR1SpPv7AXwPeKYPz10MoZvxXDyoNw/vNZQeRDpO5LOuQWzD5Sys8bbTgKhK9GIlkyQmXNxqmWswBp1J",
	"gdqmOnvkS3xSIBgSP48PFIazHoKJvXI8yNdunM5/jPDiEU3Uz4HX0I1j9WW6wavmdKi5hdKMg9+Bo1rT",
	"1QvDeVDsx5jID01j680st3Cwf6jFXwupS3xCOiAEHkrKiyD68RW3q/Mqasx3qdnhKdlUkQczjBWPc7GQ",
	"zhC3Bb67l0xGV7dTEpNlKz9yeTG5mKBrqUBQxUlKPlxMLj5gY6L20RGUZEYv8CEHRxGSRy2XYspISv4A",
	"u14mEKSXvbv5y2TitwJhQVivfVXwzN1OvhpfAT6vozeWrrBclAxMprmyPpxZlWVgzKIqIr0+FhNTlSXV",
	"Kw83upnd/R7ZBrCluUFGXZBzPJwUOOudUKQJRHwrjXXrAPE52aiIo0Q6WDXq7exbXUEdZnonGz6kOiYf",
	"j5iS7T0skI5ryqKGIfT96zl9T4UFLWgRGdBL0BF0C99aDG0WWw1gXZq1CGRlD6oAz4zJxV8yumniHmDw",
	"NkIgDM9FpfaD8MvVibQ4XCxHifHy6ABG1TzSFVXqXec9jc0aXsIiwzFt9vX3q6JwK80p2/v2zjS2tb9B",
	"rnHA0KKIbMNYy7j/PccpHyzl9f89TlTK4X+snLmct/b5AMP4Pmo2ssh0KS9W7zXd05lPZ0QjAd+jdtPu",
	"aa2r7uSZs9oPpQIsDNX3yf0d2b9eTZnb/jQtwWKXSD8/E9yH3EbYfrWl/gtuWznxBgH9PbieD2T1cTgm",
	"Xf49yGH+31wOPGuO/ejLKpp+Ctb7rrZ6ZrYnZyvi/1OrPpA7RW32OMze+pP4tAk8/hQIf8yP/8I43xSo",
	"HNL3KbBXwj6d+1XsbjgTXpyVLkhKEqp4srwk9bz+NwAA//9xQA+cvBkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
